print("สูตรคำนวณระยะทาง:v=s/t")
print("v=อัตราเร็วของการเคลื่อนที่ (m/s หรือ km/hr)")
print("t=เวลาที่วัตถุใช้เคลื่อนที่จริง (s หรือ hr)")
print("---------")
print("v=?")
v = input()
print("---------")
print("t=?")
t = input()
print("---------")
result = int(v)/int(t)
print("ระยะที่คุณเดินทาง""=",result,"km/hr")
